### ISSUE TITLE
0.2.0: pep517 build is not building DSO module

### ISSUE THREAD

**Issue by kloczek** [aio-libs/propcache#55]
### Please confirm the following

- [X] I agree to follow the [aio-libs Code of Conduct][CoC]

[CoC]: ../../.github/blob/master/CODE_OF_CONDUCT.md

- [X] I have checked the [current issues][issue search] for duplicates.

[issue search]: ../search?q=is%3Aissue&type=issues

- [X] I understand this is open source software provided for free and that I might not receive a timely response.
- [X] I am positive I am **NOT** reporting a (potential) security
vulnerability, to the best of my knowledge. *(These must be shared by
submitting [this report form][vulnerability report form] instead, if
any hesitation exists.)*

[vulnerability report form]: ../security/advisories/new

- [ ] I am willing to submit a pull request with reporoducers as xfailing test cases or even entire fix. *(Assign this issue to me.)*

### Describe the bug

Looks like pep517 based build is not producing `propcache._helpers_c` DSO module.

### To Reproduce

use `pip` or `build` modules to perform pep517 build.

### Expected behavior

build should produce DSO module.

### Logs/tracebacks

<details>
<summary>Here is build output:</summary>

```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
running egg_info
creating src/propcache.egg-info
writing src/propcache.egg-info/PKG-INFO
writing dependency_links to src/propcache.egg-info/dependency_links.txt
writing top-level names to src/propcache.egg-info/top_level.txt
writing manifest file 'src/propcache.egg-info/SOURCES.txt'
reading manifest file 'src/propcache.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'propcache'
warning: no previously-included files matching '*.cache' found anywhere in distribution
warning: no previously-included files found matching 'src/propcache/*.c'
warning: no previously-included files found matching 'src/propcache/*.html'
warning: no previously-included files found matching 'src/propcache/*.so'
warning: no previously-included files found matching 'src/propcache/*.pyd'
no previously-included directories found matching 'docs/_build'
adding license file 'LICENSE'
adding license file 'NOTICE'
writing manifest file 'src/propcache.egg-info/SOURCES.txt'
* Building wheel...
running bdist_wheel
running build
running build_py
creating build/lib/propcache
copying src/propcache/_helpers.py -> build/lib/propcache
copying src/propcache/api.py -> build/lib/propcache
copying src/propcache/__init__.py -> build/lib/propcache
copying src/propcache/_helpers_py.py -> build/lib/propcache
running egg_info
writing src/propcache.egg-info/PKG-INFO
writing dependency_links to src/propcache.egg-info/dependency_links.txt
writing top-level names to src/propcache.egg-info/top_level.txt
reading manifest file 'src/propcache.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'propcache'
warning: no previously-included files matching '*.cache' found anywhere in distribution
warning: no previously-included files found matching 'src/propcache/*.c'
warning: no previously-included files found matching 'src/propcache/*.html'
warning: no previously-included files found matching 'src/propcache/*.so'
warning: no previously-included files found matching 'src/propcache/*.pyd'
no previously-included directories found matching 'docs/_build'
adding license file 'LICENSE'
adding license file 'NOTICE'
writing manifest file 'src/propcache.egg-info/SOURCES.txt'
copying src/propcache/_helpers_c.pyx -> build/lib/propcache
copying src/propcache/py.typed -> build/lib/propcache
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/propcache
copying build/lib/propcache/_helpers.py -> build/bdist.linux-x86_64/wheel/./propcache
copying build/lib/propcache/api.py -> build/bdist.linux-x86_64/wheel/./propcache
copying build/lib/propcache/__init__.py -> build/bdist.linux-x86_64/wheel/./propcache
copying build/lib/propcache/_helpers_py.py -> build/bdist.linux-x86_64/wheel/./propcache
copying build/lib/propcache/_helpers_c.pyx -> build/bdist.linux-x86_64/wheel/./propcache
copying build/lib/propcache/py.typed -> build/bdist.linux-x86_64/wheel/./propcache
running install_egg_info
Copying src/propcache.egg-info to build/bdist.linux-x86_64/wheel/./propcache-0.2.0-py3.10.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/propcache-0.2.0.dist-info/WHEEL
creating '/home/tkloczko/rpmbuild/BUILD/propcache-0.2.0/dist/.tmp-wugm27x5/propcache-0.2.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'propcache/__init__.py'
adding 'propcache/_helpers.py'
adding 'propcache/_helpers_c.pyx'
adding 'propcache/_helpers_py.py'
adding 'propcache/api.py'
adding 'propcache/py.typed'
adding 'propcache-0.2.0.dist-info/LICENSE'
adding 'propcache-0.2.0.dist-info/METADATA'
adding 'propcache-0.2.0.dist-info/NOTICE'
adding 'propcache-0.2.0.dist-info/WHEEL'
adding 'propcache-0.2.0.dist-info/top_level.txt'
adding 'propcache-0.2.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built propcache-0.2.0-py3-none-any.whl
```
</details>

### Python Version

```console
$ python --version
Python 3.10.14
```

### propcache Version

```console
0.2.0
```

### OS

Linux x86/64

### Additional context

<details>
<summary>List of installed modules in build env:</summary>

```console
Package                       Version
----------------------------- ------------
alabaster                     0.7.16
babel                         2.16.0
build                         1.2.2.post1
charset-normalizer            3.3.2
click                         8.1.7
Cython                        3.0.11
defusedxml                    0.7.1
distro                        1.9.0
docutils                      0.21.2
exceptiongroup                1.1.3
expandvars                    0.12.0
imagesize                     1.4.1
importlib_metadata            8.0.0
incremental                   22.10.0
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.4
markdown-it-py                3.0.0
MarkupSafe                    3.0.1
mdit-py-plugins               0.4.2
mdurl                         0.1.2
myst-parser                   4.0.0
packaging                     24.0
pluggy                        1.5.0
Pygments                      2.18.0
pyproject_hooks               1.2.0
pytest                        8.2.2
python-dateutil               2.9.0.post0
PyYAML                        6.0.2
requests                      2.32.3
setuptools                    75.1.0
snowballstemmer               2.2.0
Sphinx                        8.0.2
sphinxcontrib-applehelp       2.0.0
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.1.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          2.0.0
sphinxcontrib-serializinghtml 2.0.0
sphinxcontrib-towncrier       0.4.0a0
tokenize_rt                   6.0.0
tomli                         2.0.1
towncrier                     23.11.1.dev0
urllib3                       2.2.2
wheel                         0.44.0
zipp                          3.19.2
```
</details>

**Comment by webknjaz** [comment]
No, it must exist in sdist but not installed in wheel.

**Comment by kloczek** [comment]
OK.
If you have any idea how can I try to diagnose pep517 build issue please let me know.

**Comment by webknjaz** [comment]
> I cannot find in that workflow any traces of using pep517 build

`cibuildwheel` calls it: https://github.com/aio-libs/propcache/blob/02cad01/.github/workflows/reusable-build-wheel.yml#L75-L81
It's configured to run `python -m build` (as opposed to `pip wheel`) here: https://github.com/aio-libs/propcache/blob/02cad01/pyproject.toml#L66.
The logs from the last release show the full command: https://github.com/aio-libs/propcache/actions/runs/11214274927/job/31173924897#step:6:323.

See https://cibuildwheel.pypa.io for more information. You can `pip install` it and run locally to reproduce what's happening in the CI. It'll use the corresponding `manylinux` / `musllinux` containers per spec.

**Comment by webknjaz** [comment]
It is tested with both C-ext and pure-python in CI. There's a pytest flag for selecting the corresponding mode. Use it, if you need.

**Comment by kloczek** [comment]
Again .. by default DSO is not build and test suite by default is needed.
Also documentation looks like needs DSO:
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v8.1.3
loading translations [en]... done
making output directory... done
loading intersphinx inventory 'python' from https://docs.python.org/3/objects.inv ...
myst v4.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, links_external_new_tab=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_sort=True, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 5 added, 0 changed, 0 removed
reading sources... [ 20%] api
reading sources... [ 40%] changes
reading sources... [ 60%] contributing/guidelines
reading sources... [ 80%] contributing/release_guide
reading sources... [100%] index

/home/tkloczko/rpmbuild/BUILD/propcache-0.2.0/docs/changes.rst:12: ERROR: Command exited unexpectedly.

Command: /usr/bin/python3 -m towncrier build --draft --version '\ |release| [UNRELEASED DRAFT]'
Return code: 1

Standard output:
ERROR: tried to import propcache, but ran into this error: No module named 'propcache'


Standard error:
Loading template...
Finding news fragments...
Rendering news fragments...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/towncrier/_project.py", line 21, in _get_package
    module = import_module(package)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'propcache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/towncrier/__main__.py", line 6, in <module>
    cli()
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/towncrier/build.py", line 123, in _main
    return __main(
  File "/usr/lib/python3.10/site-packages/towncrier/build.py", line 206, in __main
    project_name = get_project_name(
  File "/usr/lib/python3.10/site-packages/towncrier/_project.py", line 69, in get_project_name
    module = _get_package(package_dir, package)
  File "/usr/lib/python3.10/site-packages/towncrier/_project.py", line 28, in _get_package
    module = import_module(package)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'propcache' [docutils]
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets...
copying assets: done
writing... python-propcache.3 {
 api
  changes
   contributing/guidelines
    contributing/release_guide
} done
build succeeded, 1 warning.
```
IMO it would be good to change build options to generate DSO.

I've tested build with missing params and build still is not producing DSO.

<details>

```console
+ /usr/bin/python3 -sBm build -w --no-isolation --config-setting=pure-python=false --config-setting=with-cython-tracing=false
* Getting build dependencies for wheel...
running egg_info
creating src/propcache.egg-info
writing src/propcache.egg-info/PKG-INFO
writing dependency_links to src/propcache.egg-info/dependency_links.txt
writing top-level names to src/propcache.egg-info/top_level.txt
writing manifest file 'src/propcache.egg-info/SOURCES.txt'
reading manifest file 'src/propcache.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'propcache'
warning: no previously-included files matching '*.cache' found anywhere in distribution
warning: no previously-included files found matching 'src/propcache/*.c'
warning: no previously-included files found matching 'src/propcache/*.html'
warning: no previously-included files found matching 'src/propcache/*.so'
warning: no previously-included files found matching 'src/propcache/*.pyd'
no previously-included directories found matching 'docs/_build'
adding license file 'LICENSE'
adding license file 'NOTICE'
writing manifest file 'src/propcache.egg-info/SOURCES.txt'
* Building wheel...
running bdist_wheel
running build
running build_py
creating build/lib/propcache
copying src/propcache/_helpers.py -> build/lib/propcache
copying src/propcache/api.py -> build/lib/propcache
copying src/propcache/__init__.py -> build/lib/propcache
copying src/propcache/_helpers_py.py -> build/lib/propcache
running egg_info
writing src/propcache.egg-info/PKG-INFO
writing dependency_links to src/propcache.egg-info/dependency_links.txt
writing top-level names to src/propcache.egg-info/top_level.txt
reading manifest file 'src/propcache.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'propcache'
warning: no previously-included files matching '*.cache' found anywhere in distribution
warning: no previously-included files found matching 'src/propcache/*.c'
warning: no previously-included files found matching 'src/propcache/*.html'
warning: no previously-included files found matching 'src/propcache/*.so'
warning: no previously-included files found matching 'src/propcache/*.pyd'
no previously-included directories found matching 'docs/_build'
adding license file 'LICENSE'
adding license file 'NOTICE'
writing manifest file 'src/propcache.egg-info/SOURCES.txt'
copying src/propcache/_helpers_c.pyx -> build/lib/propcache
copying src/propcache/py.typed -> build/lib/propcache
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/propcache
copying build/lib/propcache/_helpers.py -> build/bdist.linux-x86_64/wheel/./propcache
copying build/lib/propcache/api.py -> build/bdist.linux-x86_64/wheel/./propcache
copying build/lib/propcache/__init__.py -> build/bdist.linux-x86_64/wheel/./propcache
copying build/lib/propcache/_helpers_py.py -> build/bdist.linux-x86_64/wheel/./propcache
copying build/lib/propcache/_helpers_c.pyx -> build/bdist.linux-x86_64/wheel/./propcache
copying build/lib/propcache/py.typed -> build/bdist.linux-x86_64/wheel/./propcache
running install_egg_info
Copying src/propcache.egg-info to build/bdist.linux-x86_64/wheel/./propcache-0.2.0-py3.10.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/propcache-0.2.0.dist-info/WHEEL
creating '/home/tkloczko/rpmbuild/BUILD/propcache-0.2.0/dist/.tmp-8hvvjfuz/propcache-0.2.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'propcache/__init__.py'
adding 'propcache/_helpers.py'
adding 'propcache/_helpers_c.pyx'
adding 'propcache/_helpers_py.py'
adding 'propcache/api.py'
adding 'propcache/py.typed'
adding 'propcache-0.2.0.dist-info/LICENSE'
adding 'propcache-0.2.0.dist-info/METADATA'
adding 'propcache-0.2.0.dist-info/NOTICE'
adding 'propcache-0.2.0.dist-info/WHEEL'
adding 'propcache-0.2.0.dist-info/top_level.txt'
adding 'propcache-0.2.0.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built propcache-0.2.0-py3-none-any.whl
```
</details>

**Comment by kloczek** [comment]
BTW looks like packaging/pep517_backend/_backend.py is using `distutils` which is deprecated.

**Comment by webknjaz** [comment]
That's needed to patch what setuptools wraps. Also, historically, we had C-extensions as opt-in to facilitate installs in environments where it would be difficult for the users to get a build toolchain. We expect that they would use our wheels when available, though. Pure-python is a good fallback for them. Toggling a default would break that promise.
The same goes for tests — they are for us to ensure that all's checked correctly, so they must default to C-extensions. It's all controlled in all the right places. Downstreams must make their own choices — that's out of the scope of upstream maintenance.

**Comment by kloczek** [comment]
> > Also documentation looks like needs DSO:
> > [..]
> > ```
> > ERROR: tried to import propcache, but ran into this error: No module named 'propcache'
> > ```
> 
> No, it doesn't: https://app.readthedocs.org/projects/propcache/builds/25944844/#247291069--1. But it has to be available, and in your case it's not.

Moment so you want to day that to build `propcache` I need to INSTALL first `propcache`? 🤔 
How?
PEP517 build should relay only on content  of source tree. Isn't it 🤔
